function getVerben() {
  return [
    {"infinitiv":"あう","praesens":"あいます","praeteritum":"あって","perfekt":"あわない","meaning":"to meet"},
    {"infinitiv":"いう","praesens":"いいます","praeteritum":"いって","perfekt":"いわない","meaning":"to say"},
    {"infinitiv":"かう","praesens":"かいます","praeteritum":"かって","perfekt":"かわない","meaning":"to buy"},
    {"infinitiv":"つかう","praesens":"つかいます","praeteritum":"つかって","perfekt":"つかわない","meaning":"to use"},
    {"infinitiv":"いく","praesens":"いきます","praeteritum":"いって","perfekt":"いかない","meaning":"to go"},
    {"infinitiv":"かく","praesens":"かきます","praeteritum":"かいて","perfekt":"かかない","meaning":"to write, to paint"},
    {"infinitiv":"きく","praesens":"ききます","praeteritum":"きいて","perfekt":"きかない","meaning":"to hear, to listen"},
    {"infinitiv":"なく","praesens":"なきます","praeteritum":"ないて","perfekt":"なかない","meaning":"to cry"},
    {"infinitiv":"いそぐ","praesens":"いそぎます","praeteritum":"いそいで","perfekt":"いそがない","meaning":"to hurry"},
    {"infinitiv":"およぐ","praesens":"およぎます","praeteritum":"およいで","perfekt":"およがない","meaning":"to swim"},
    {"infinitiv":"かぐ","praesens":"かぎます","praeteritum":"かいで","perfekt":"かがない","meaning":"to sniff"},
    {"infinitiv":"おす","praesens":"おします","praeteritum":"おして","perfekt":"おさない","meaning":"to push"},
    {"infinitiv":"なおす","praesens":"なおします","praeteritum":"なおして","perfekt":"なおさない","meaning":"to fix"},
    {"infinitiv":"はなす","praesens":"はなします","praeteritum":"はなして","perfekt":"はなさない","meaning":"to talk; to speak"},
    {"infinitiv":"たつ","praesens":"たちます","praeteritum":"たって","perfekt":"たたない","meaning":"to stand"},
    {"infinitiv":"まつ","praesens":"まちます","praeteritum":"まって","perfekt":"またない","meaning":"to wait"},
    {"infinitiv":"あそぶ","praesens":"あそびます","praeteritum":"あそんで","perfekt":"あそばない","meaning":"to play"},
    {"infinitiv":"とぶ","praesens":"とびます","praeteritum":"とんで","perfekt":"とばない","meaning":"to fly"},
    {"infinitiv":"よぶ","praesens":"よびます","praeteritum":"よんで","perfekt":"よばない","meaning":"to call; to invite"},
    {"infinitiv":"すむ","praesens":"すみます","praeteritum":"すんで","perfekt":"すまない","meaning":"to live"},
    {"infinitiv":"のむ","praesens":"のみます","praeteritum":"のんで","perfekt":"のまない","meaning":"to drink"},
    {"infinitiv":"よむ","praesens":"よみます","praeteritum":"よんで","perfekt":"よまない","meaning":"to read"},
    {"infinitiv":"あける","praesens":"あけます","praeteritum":"あけて","perfekt":"あけない","meaning":"to open"},
    {"infinitiv":"いる","praesens":"います","praeteritum":"いて","perfekt":"ない","meaning":"to be; to exist"},
    {"infinitiv":"おきる","praesens":"おきます","praeteritum":"おきて","perfekt":"おきない","meaning":"to get up"},
    {"infinitiv":"おどる","praesens":"おどります","praeteritum":"おどって","perfekt":"おどらない","meaning":"to dance"},
    {"infinitiv":"かいものする","praesens":"かいものします","praeteritum":"かいものして","perfekt":"かいものしない","meaning":"to do shopping"},
    {"infinitiv":"かえる","praesens":"かえります","praeteritum":"かえって","perfekt":"かえらない","meaning":"to return; to come back / home"},
    {"infinitiv":"くる","praesens":"きます","praeteritum":"きて","perfekt":"こない","meaning":"to come"},
    {"infinitiv":"しまる","praesens":"しまります","praeteritum":"しまって","perfekt":"しまらない","meaning":"to be close"},
    {"infinitiv":"しめる","praesens":"しめます","praeteritum":"しめて","perfekt":"しめない","meaning":"to close"},
    {"infinitiv":"する","praesens":"します","praeteritum":"して","perfekt":"しない","meaning":"to do"},
    {"infinitiv":"たべる","praesens":"たべます","praeteritum":"たべて","perfekt":"たべない","meaning":"to eat"},
    {"infinitiv":"つくる","praesens":"つくります","praeteritum":"つくって","perfekt":"つくらない","meaning":"to make"},
    {"infinitiv":"でる","praesens":"でます","praeteritum":"でて","perfekt":"でない","meaning":"to leave; to go out"},
    {"infinitiv":"とる","praesens":"とります","praeteritum":"とって","perfekt":"とらない","meaning":"to take; to pick up"},
    {"infinitiv":"ねる","praesens":"ねます","praeteritum":"ねて","perfekt":"ねない","meaning":"to sleep"},
    {"infinitiv":"のる","praesens":"のります","praeteritum":"のって","perfekt":"のらない","meaning":"to get on (train); to board"},
    {"infinitiv":"はいる","praesens":"はいります","praeteritum":"はいって","perfekt":"はいらない","meaning":"to enter; to get into"},
    {"infinitiv":"はしる","praesens":"はしります","praeteritum":"はしって","perfekt":"はしらない","meaning":"to run"},
    {"infinitiv":"べんきょうする","praesens":"べんきょうします","praeteritum":"べんきょうして","perfekt":"べんきょうしない","meaning":"to study"},
    {"infinitiv":"みる","praesens":"みます","praeteritum":"みて","perfekt":"みない","meaning":"to see; to look"},
    {"infinitiv":"りょこうする","praesens":"りょこうします","praeteritum":"りょこうして","perfekt":"りょこうしない","meaning":"to travel"},
    {"infinitiv":"りょうりする","praesens":"りょうりします","praeteritum":"りょうりして","perfekt":"りょうりしない","meaning":"to cook"},
    {"infinitiv":"わかる","praesens":"わかります","praeteritum":"わかって","perfekt":"わからない","meaning":"to understand"}
  ]
}